config/routes.rb
Rails.application.routes.draw do
  #get 'info/infogem'
  #get 'info/infoauthor'
  #get 'info/infolatestgems'
  root 'welcome#index'
  match 'searchgem', to: 'info#infogem', via: [:get, :post]
  match 'searchauthor', to: 'info#infoauthor', via: [:get, :post]
  match 'searchlatest', to: 'info#infolatestgems', via: [:get, :post]
  resources :dependencies
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dependency.rb
class Dependency < ApplicationRecord
    include Rails.application.routes.url_helpers
end

app/models/rubygemsorg.rb
class RubyGemsOrg #nodoc
  include HTTParty
  include JSON
  def self.get_gem_info(name)
    url = "https://rubygems.org/api/v1/gems/#{name}.json"
    response = HTTParty.get(url)
    responsebody = JSON.parse(response.body)
    responsebody # does this return?
  end

  def self.get_gems_of_author(name)
    url = "https://rubygems.org/api/v1/owners/#{name}/gems.json"
    response = HTTParty.get(url)
    responsebody = JSON.parse(response.body)
    responsebody
  
  end

  def self.get_latest
    url = "https://rubygems.org/api/v1/activity/latest.json"
    response = HTTParty.get(url)
    responsebody = JSON.parse(response.body)
    responsebody
  end
end
quit

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/dependencies_controller.rb
class DependenciesController < ApplicationController
  before_action :set_dependency, only: [:show, :edit, :update, :destroy]

  # GET /dependencies
  # GET /dependencies.json
  def index
    @dependencies = Dependency.all
  end

  # GET /dependencies/1
  # GET /dependencies/1.json
  def show
  end

  # GET /dependencies/new
  def new
    @dependency = Dependency.new
  end

  # GET /dependencies/1/edit
  def edit
  end

  # POST /dependencies
  # POST /dependencies.json
  def create
    @dependency = Dependency.new(dependency_params)

    respond_to do |format|
      if @dependency.save
        format.html { redirect_to @dependency, notice: 'Dependency was successfully created.' }
        format.json { render :show, status: :created, location: @dependency }
      else
        format.html { render :new }
        format.json { render json: @dependency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dependencies/1
  # PATCH/PUT /dependencies/1.json
  def update
    respond_to do |format|
      if @dependency.update(dependency_params)
        format.html { redirect_to @dependency, notice: 'Dependency was successfully updated.' }
        format.json { render :show, status: :ok, location: @dependency }
      else
        format.html { render :edit }
        format.json { render json: @dependency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dependencies/1
  # DELETE /dependencies/1.json
  def destroy
    @dependency.destroy
    respond_to do |format|
      format.html { redirect_to dependencies_url, notice: 'Dependency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dependency
      @dependency = Dependency.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dependency_params
      params.require(:dependency).permit(:name, :authors, :version)
    end
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  require 'rubygemsorg'
  def infogem
    if params[:search_gem].to_s.present?
      name = params[:search_gem]
      response = RubyGemsOrg.get_gem_info(name)
      name = response['name']
      @dependency = Dependency.find_by(:name => name)
      @dependency = Dependency.create(:name=>response["name"],:authors=>response["authors"],:version=>response["version"])
    else
    redirect_to(root_url)  
    end
  end

  def infoauthor
    if params[:search_author].to_s.present?
      @author = params[:search_author]
      @response = RubyGemsOrg.get_gems_of_author(@author)

    else
        redirect_to(root_url)
    end
  end

  def infolatestgems
    @latest = RubyGemsOrg.get_latest 
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dependencies_helper.rb
module DependenciesHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dependencies/_form.html.erb
<%= form_with(model: dependency, local: true) do |form| %>
  <% if dependency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dependency.errors.count, "error") %> prohibited this dependency from being saved:</h2>

      <ul>
        <% dependency.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :authors %>
    <%= form.text_field :authors %>
  </div>

  <div class="field">
    <%= form.label :version %>
    <%= form.text_field :version %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dependencies/edit.html.erb
<h1>Editing Dependency</h1>

<%= render 'form', dependency: @dependency %>

<%= link_to 'Show', @dependency %> |
<%= link_to 'Back', dependencies_path %>

app/views/dependencies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dependencies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Authors</th>
      <th>Version</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dependencies.each do |dependency| %>
      <tr>
        <td><%= dependency.name %></td>
        <td><%= dependency.authors %></td>
        <td><%= dependency.version %></td>
        <td><%= link_to 'Show', dependency %></td>
        <td><%= link_to 'Edit', edit_dependency_path(dependency) %></td>
        <td><%= link_to 'Destroy', dependency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dependency', new_dependency_path %>

app/views/dependencies/new.html.erb
<h1>New Dependency</h1>

<%= render 'form', dependency: @dependency %>

<%= link_to 'Back', dependencies_path %>

app/views/dependencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dependency.name %>
</p>

<p>
  <strong>Authors:</strong>
  <%= @dependency.authors %>
</p>

<p>
  <strong>Version:</strong>
  <%= @dependency.version %>
</p>

<%= link_to 'Edit', edit_dependency_path(@dependency) %> |
<%= link_to 'Back', dependencies_path %>

app/views/info/infoauthor.html.erb
<h1>Info#infoauthor</h1>
<p>Find me in app/views/info/infoauthor.html.erb</p>
<h3>Gems developed by <%= @author %> </h3>
<table>
  <thead>
    <tr>
      <th>Gem Name</th>
      <th>Version</th>
      <th>Info</th>
      <th>Project URI</th>
      <th># Total Downloads</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% @response.each do |result| %>
        <td><%= result["name"] %></td>
        <td><%= result["version"] %></td>
        <td><%= result["info"] %></td>
        <td><%= result["project_uri"] %></td>
        <td><%= result["downloads"] %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<br>
<%= link_to 'Home', root_path %>

app/views/info/infogem.html.erb
<h1>Info#infogem</h1>
<p>Find me in app/views/info/infogem.html.erb</p>
<h3>Gem Details</h3>
<p>Name: <%= @dependency.name %></p>
<p>Authors: <%= @dependency.authors %></p>
<p>Version: <%= @dependency.version %></p>
<%= link_to 'Home', root_path %>
<%= link_to 'Show Application Dependencies', dependencies_path %> <br>

app/views/info/infolatestgems.html.erb
<h1>Info#infolatestgems</h1>
<p>Find me in app/views/info/infolatestgems.html.erb</p>
<h3>Latest Gems</h3>
<table>
  <thead>
    <tr>
      <th>Gem Name</th>
      <th>Version</th>
      <th>Info</th>
      <th>Project URI</th>
      <th># Total Downloads</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% @latest.each do |result| %>
        <td><%= result["name"] %></td>
        <td><%= result["version"] %></td>
        <td><%= result["info"] %></td>
        <td><%= result["project_uri"] %></td>
        <td><%= result["downloads"] %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<br>
<%= link_to 'Home', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<%= form_tag("searchgem", method: "post") do %>
  <%= label_tag(:search_gem, "Search for gem:") %>
  <%= text_field_tag(:search_gem) %><%= submit_tag("Search gem") %>
<% end %>

<%= form_tag("searchauthor", method: "post") do %>
  <%= label_tag(:search_author, "Search for all gems by author") %>
  <%= text_field_tag(:search_author) %>
  <%= submit_tag("Search Author") %>
<% end %>

<%= form_tag("searchlatest", method: "post") do %>
  <%= label_tag(:search_author, "Latest Gems on the Site") %>
  <%= submit_tag("Search Latest") %>
<% end %>